name: ikvm-docs

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
      - name: Install
        run: npm install
      - name: Generate
        run: npm run generate
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: .output/public
